* Living Well Inside Tails Gnu/Linux

** NOTICE OF GitHub FAILURE
  - As of 2026-10-01 GitHub is failing to correctly display this document!
  - See the section below titled: ** Availability Of This Document


For some time I've wanted to build a Gnu/Linux environment which was
- Entirely resident on a USB Thumbdrive
- Secure and private, like Tails
- Everything I do should persist on the Thumbdrive
    - projects
    - packages
    - customizations

Given the available USB Thumbdrives
    - 500GB for $50!
there is no reason why a Gnu/Linux environment living on such can't be
every bit as good as a normally installed Gnu/Linux environment.

Alas, [[file:tails-issues.org][Tails presents obstacles]] for using it this way.

This project is an attempt to overcome these obstacles!

As I overcome various obstacles to achieving these goals I intend to
document them here.

Here's my [[file:ROADMAP.org][Project Roadmap]].

It's also still not clear if I'm going to be able to fully achieve my
goals.  An alternative would be to use a more ordinary Gnu/Linux
distribution in encrypted partitions and add tor, etc.
** Availability Of This Document

This document is normally available at all the following urls:
- Codeberg :: 
- GitLab :: 
- GitHub ::
  - GitHub is currently failing to correctly process OrgMode documents.
  - as of 2026-10-01

Please consult the LICENCE or LICENSE.org or LICENSE.md file at the
top of this repository for freedoms and restrictions in your use of
the contents of this repository, including this document.

Even when not required, we would appreciate
- attribution with a reference to our respository,
- your sending us any improvements you make to these materials,
- information about any significant usage of these materials in your projects,
- and thank you!
