* Tails Linux Living /Project Roadmap/

The directory structure shown here appears excessively complex because
it is only a small subset of the full structure of my actual Gnu/Linux
home!

** DONE Populate =~= and =~/Desktop=

Tails has a mechanism for populating files under =~= but it is
somewhat inflexible.  Tails also provides an imnsho excessively long
=.bashrc= file.  I prefer a more modular solution.  I also prefer to
manage /everything/ with =git=.

- [[file:Links/HomeLinks/.bash_profile][.bash_profile]]
- [[file:Links/HomeLinks/.bashrc][.bashrc]]
- [[file:SW/Config/Bin/restore-dotfiles][restore-dotfiles]]

** TODO Persist PostgreSQL Databases

So far we have all of the required packages installed.

The databases live under
- =/var/lib/postgresql/11/main/base/=
and are owned by user =postgres=.

Strategies
- Have them live somewhere persistent
    - have Tails restore the link to them
    - have the link to them baked in

** DONE Get Firefox working with =tor=

see solution in [[file:tails-issues.org][tails-issues.org]]

For any website where one has an account
- The Tor Browser is a pita
- Firefox Multi-Account Containers are perfect!

** TODO Get the Tails Gnome Shell up to my standards

I'm used to
- Some nice customizations
- Built with the Mint Maté Desktop

Let's see how much we can replicate such niceness.

** TODO Get Emacs using =tor= comfortably

I spend more time in Emacs than in any other application

** TODO Get an encrypted swapfile!

I need a cushion when I use lots of processes!
  
** DONE Backups and Resilience

Everything important on my Tails thumbdrive is inside of a Git repository and
gets regularly pushed to a private offsite repository. Yet reconstructing
everything just from those repositories would still be a pain.
   
I have two Tails thumbdrives with identical Tails distributions. The one I use
regularly has a small form factor, only barely sticking out from its USB slot.

From time to time I backup my little Tails thumbdrive on a larger (and slightly
cheaper) backup Tails using =rsync= as detailed in

[[https://tails.boum.org/doc/first_steps/persistence/backup/index.en.html][- Tail's Backup Procedure]]

It's possible to do a backup from a non-graphical console if the Graphical
console is not working, but beware of propagating the cause of the error! It's
not too hard to just backup what's changed to a subdirectory or to somewhere
else.
